services:
  Architect\ContaoCommandBundle\Command\MakeControllerCommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Architect\ContaoCommandBundle\Command\AddControllerConfigurationCommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Architect\ContaoCommandBundle\Command\MakeTemplateCommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Architect\ContaoCommandBundle\Command\AddControllerDCACommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Architect\ContaoCommandBundle\Command\MakeContentElementCommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Architect\ContaoCommandBundle\Command\MakeFrontendModuleCommand:
    arguments:
      - '@contao.framework'
    tags:
      - { name: 'console.command' }

  Dotenv:
    class: Symfony\Component\Dotenv\Dotenv

  Architect\ContaoCommandBundle\Command\CreateBundleCommand:
    arguments:
      $framework: '@contao.framework'
      $parameterBag: '@parameter_bag'
      $dotenv: '@Dotenv'
    tags:
      - { name: 'console.command' }